services:
  astro:
    image: oven/bun:latest
    container_name: astro_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    command: >
      sh -c "bun install && bun run dev"
